name: Iris ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Train model with MLflow
        run: python train.py

      - name: Evaluate model
        run: python evaluate.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4   # <-- nouvelle version
        with:
          name: mlflow-runs
          path: mlruns
